; Special characters using right alt modifier
>!;::send æ
>!+;::send Æ
>!'::send ø
>!"::send Ø
>![::send å
>!{::send Å
>!o::send Ω
>!d::send °
>!+d::send 📄
>!u::send µ
>!1::send ☐
>!2::send ☑
>!e::send €
>!w::send ⚠
>!b::send 🐛
>!l::send ⚡
>!t::send 👍
>!f::send 🚩
>!c::send 📅
>!i::send 💡
>!+m::send ✓
>!m::send ✔
>!n::send ❌
>!.::send ·
>!-::send –
>!p::send π
>!q::send œ
>!+q::send Œ
>!3::send 🧑
>!4::send 📦
>!5::send ⚙
>!x::send ×
>!LEFT::send ←
>!UP::send ↑
>!RIGHT::send →
>!DOWN::send ↓
>!Numpad1::send └
>!Numpad2::send ┴
>!Numpad3::send ┘
>!Numpad4::send ├
>!Numpad5::send ┼
>!Numpad6::send ┤
>!Numpad7::send ┌
>!Numpad8::send ┬
>!Numpad9::send ┐
>!NumpadSub::send ─
>!NumpadAdd::send │
>!+::send ±
